<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <!-- Package metadata -->
        <PackageId>InfiniLore.Lucide.Data</PackageId>
        <Version>0.12.477</Version>
        <Authors>Anna Sas</Authors>
        <Description>Use Lucide in your Blazor apps</Description>
        <PackageProjectUrl>https://github.com/InfiniLore/lucide.blazor</PackageProjectUrl>
        <PackageTags>lucide;blazor;icon</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
		<PackageOutputPath>../../nupkg</PackageOutputPath>
        
        <!-- Define a fallback if NODE_PATH isn't set -->
        <LucideIconsPath Condition=" '$(NODE_PATH)' != '' ">$(NODE_PATH)/lucide-static/icons/**/*.svg</LucideIconsPath>
        <LucideIconsPath Condition=" '$(NODE_PATH)' == '' ">$(MSBuildProjectDirectory)/../../node_modules/lucide-static/icons/**/*.svg</LucideIconsPath>
	</PropertyGroup>

    <!-- Include external files -->
    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../README.md" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\InfiniLore.Lucide.Generators.Raw\InfiniLore.Lucide.Generators.Raw.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup Label="Lucide Files">
        <!-- Adjusted to ensure paths resolve dynamically -->
        <AdditionalFiles Include="$(LucideIconsPath)"
                         Link="Icons\%(RecursiveDir)%(FileName)%(Extension)"/>
    </ItemGroup>

    <!-- Package dependencies -->
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.13.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" PrivateAssets="all" />
        <PackageReference Include="CodeOfChaos.GeneratorTools" Version="1.4.1" Pack="true" GeneratePathProperty="true" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Label="Packing">
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

        <!-- Exclude additional files from NuGet package -->
        <None Include="..\..\..\node_modules/lucide-static/icons/**/*.svg" Pack="false" />
        <Analyzer Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll" Pack="false" />
    </ItemGroup>

</Project>
